### ISSUE TITLE
[Due for payment 2026-09-30] Add iOS prebuilt RN artifacts support on standalone NewDot

### ISSUE THREAD

**Issue by MelvinBot** [Expensify/App#98383]
Follow-up to Expensify/App#86437.

## Background
iOS prebuilt React Native artifacts are being rolled out on HybridApp first. Standalone NewDot support was intentionally deferred because it is a non-trivial change (e.g. something rewrites the module map during the build, breaking compilation because the compiler can no longer find the `React` module — for example Swift imports like `import React_RCTAppDelegate`).

## Task
Add support for consuming iOS prebuilt RN artifacts on standalone NewDot.

Note: this is lower priority than HybridApp, since HybridApp is what we build in CI/CD and typically for native package bumps.

<details><summary>Issue Owner</summary>Current Issue Owner: @mkhutornyi</details>

**Comment by mateuuszzzzz** [comment]
Update: I started looking into this and am exploring a few clean approaches. So far, the best option I’ve found is to update the Swift modulemap directly, similar to what Expo does. This would make the required artifacts visible to Swift, allowing the import in our standalone app’s Swift RCTAppDelegate to resolve correctly during compilation.

**Comment by roryabraham** [comment]
any update @mateuuszzzzz ?

**Comment by mateuuszzzzz** [comment]
I tested a few more approaches, and so far, editing the modulemap seems to be the only reliable one, so I’m sticking with this direction. There are a few compilation errors along the way, which I’m working on fixing right now. Once everything is sorted out, I’ll raise a PR (hopefully soon)

**Comment by mateuuszzzzz** [comment]
I’ve opened a draft PR to test how standalone NewDot works with our artifacts. The app compiles without any issues, so I’m now inspecting how it behaves at runtime

**Comment by mkhutornyi** [comment]
# Contributor+ Checklist:

- [x] **[Contributor]** The offending PR and associated issue have been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake.

    Link to the comment on the PR:
    Link to the comment on the Issue:

- [x] **[Contributor]** If the regression was CRITICAL (e.g. interrupts a core flow) A discussion in [#expensify-open-source](https://app.slack.com/client/E047TPA624F/C01GTK53T8Q) has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner.

    Link to discussion:

- [x] **[Contributor]** If it was decided to create a regression test for the bug, please propose the [regression test](https://github.com/Expensify/App/blob/main/contributingGuides/REGRESSION_TEST_BEST_PRACTICES.md) steps using the template below to ensure the same bug will not reach production again.

## Regression Test Proposal
No need regressin test. Neither bug nor new feature.
