### ISSUE TITLE
Chat - Whisper invite options are not scrollable horizontally on small screen

### ISSUE THREAD

**Issue by mitarachim** [Expensify/App#69703]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.2.1-0
**Reproducible in staging?:** Yes
**Reproducible in production?:** No
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://github.com/Expensify/App/pull/69333
**Email or phone of affected tester (no customers):** sjdiosjnojdsojsd@gmail.com
**Issue reported by:** Applause Internal Team
**Device used:** Samsung Galaxy Z Fold 4 / Android 15
**App Component:** Chat Report View

## Action Performed:
1. Launch Expensify app.
2. Go to workspace chat.
3. Mention someone who is not a member of workspace chat and send it.
4. Try to scroll the whisper options horizontally.

## Expected Result:
The whisper options can be scrolled horizontally.

## Actual Result:
The whisper options cannot be scrolled horizontally. Do nothing option is missing as a result.

## Workaround:
Unknown

## Platforms:
- [x] Android: App
- [x] Android: mWeb Chrome
- [x] iOS: App
- [x] iOS: mWeb Safari
- [x] iOS: mWeb Chrome
- [ ] Windows: Chrome
- [ ] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/922fe314-af92-410c-a80d-f252911e7fd7

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by rlinoz** [comment]
Caused by https://github.com/Expensify/App/pull/69322

cc: @thelullabyy @eVoloshchak

**Comment by rlinoz** [comment]
Sure!

**Comment by rlinoz** [comment]
Thanks!
