### ISSUE TITLE
[HOLD for payment 2024-11-01] [$250] The "New messages" floating button doesn't scroll to bottom for actionable whispers

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#49825]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 9.0.40-1
**Reproducible in staging?:** y
**Reproducible in production?:** y
**If this was caught during regression testing, add the test name, ID and link from TestRail:**
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** @paultsimura 
**Slack conversation:** https://expensify.slack.com/archives/C049HHMV9SM/p1727285468531329

## Action Performed:
1. Create a room;
2. Mention a user that is not a member of this room using the `@{user}` syntax;
3. Notice the actionable whisper "Heads up, {user} isn't a member of this room" message appears;
4. Verify the "New messages" floating button appears;
5. Scroll up a little;
6. Click the "New messages" floating button;

## Expected Result:
The report is scrolled to the bottom so the whisper action becomes visible.
## Actual Result:
The report is not scrolled.
## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/user-attachments/assets/4b3c7ae4-760e-482b-a01c-7e1b6937c643

https://github.com/user-attachments/assets/bd618e6b-cfd4-45fc-be5b-aa0e283f05bf

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~021839443131047584238</li>
        <li>Upwork Job ID: 1839443131047584238</li>
        <li>Last Price Increase: 2024-10-10</li>
<li>Automatic offers: </li>
<ul>
<li>situchan | Reviewer | 104361028</li>
</ul></li>
    </ul>
</details>

<details><summary>Issue Owner</summary>Current Issue Owner: @trjExpensify</details>

**Comment by trjExpensify** [comment]
Yeah, that's strange.

**Comment by raza-ak** [comment]
### Please re-state the problem that we are trying to solve in this issue.
The "New messages" floating button doesn't scroll to bottom for actionable whispers
### What is the root cause of that problem?
The issue is rooted in the `ReportActionsList` component. Specifically, the `scrollToBottomAndMarkReportAsRead` function is not initiating the scroll when the `hasNewestReportAction` value is false.

### What changes do you think we should make in order to solve the problem?
Modify the component logic to ensure that clicking the "New Messages" floating button triggers the scroll functionality. If `hasNewestReportAction` is false, we explicitly call the `scrollToBottom` function to ensure that the latest messages or chats are displayed.
**Code Changes:**

In the src/pages/home/report/ReportActionsList.tsx file, update the logic as follows:
<img width="662" alt="image" src="https://github.com/user-attachments/assets/0188d7b1-d8f2-446d-b5f8-f21ebce7df10">

This change ensures that the latest message/chat is visible when `hasNewestReportAction` is false, effectively resolving the scrolling issue.
**Video:**

https://github.com/user-attachments/assets/b9e92069-f7e0-4db9-9693-b38b05bfb550

**Comment by klajdipaja** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The "New Message" button should scroll down to the bottom when clicked but only for whisper messages it does not. 
### What is the root cause of that problem?
The function that handles the scroll to bottom is the one below:
```
    const scrollToBottomAndMarkReportAsRead = () => {
        if (!hasNewestReportAction) {
            Navigation.navigate(ROUTES.REPORT_WITH_ID.getRoute(report.reportID));
            Report.openReport(report.reportID);
            return;
        }
        reportScrollManager.scrollToBottom();
        readActionSkipped.current = false;
        Report.readNewestAction(report.reportID);
    };

```
The flag `hasNewestReportAction` is not working properly for whisper messages 
`hasNewestReportAction=sortedVisibleReportActions[0]?.created === report.lastVisibleActionCreated `
`sortedVisibleReportActions[0]` belongs to the whisper action but `report.lastVisibleActionCreated` to the action the user has executed. Along with that we also have the problem the the unreadMarkerTime is not set correctly since we are setting it to `sortedVisibleReportActions[0]` we are effectively setting it the whisper message created time which the user has not read yet. 


### What changes do you think we should make in order to solve the problem?
We need to modify the `useEffect` that sets the unreadMarkerTime to actually use the report date as below:

```
useEffect(() => {
        if (unreadMarkerReportActionID) {
            return;
        }

        const mostRecentReportActionCreated = report.lastVisibleActionCreated ?? '';
        if (mostRecentReportActionCreated === unreadMarkerTime) {
            return;
        }

        setUnreadMarkerTime(mostRecentReportActionCreated);

        // eslint-disable-next-line react-compiler/react-compiler, react-hooks/exhaustive-deps
    }, [sortedVisibleReportActions, report.lastVisibleActionCreated]);

```

This will make sure that the unreadMarker is updated when the `report.lastVisibleActionCreated` changes and re-render the component to update the `hasNewestReportAction` flag.

We also need to changee the logic of the `unreadMarkerReportActionID` to check if the latest message is a whisper for the current user then we should show a "New Message" marker above. The shouldDisplayNewMarker will change the return to check if the latest action is a whisper:
```
const shouldDisplayNewMarker = (reportAction: OnyxTypes.ReportAction, index: number): boolean => {
            const nextMessage = sortedVisibleReportActions[index + 1];
            const isCurrentMessageUnread = isMessageUnread(reportAction, unreadMarkerTime);
            const isNextMessageRead = !nextMessage || !isMessageUnread(nextMessage, unreadMarkerTime);
            const shouldDisplay = isCurrentMessageUnread && isNextMessageRead && !ReportActionsUtils.shouldHideNewMarker(reportAction);
            const isWithinVisibleThreshold = scrollingVerticalOffset.current < MSG_VISIBLE_THRESHOLD ? reportAction.created < (userActiveSince.current ?? '') : true;
            const isWhisperForUser = isWhisperVisibleOnlyToUser(sortedVisibleReportActions[index]);
            return shouldDisplay && (isWithinVisibleThreshold || isWhisperForUser);
        };
```

### What alternative solutions did you explore? (Optional)

https://github.com/user-attachments/assets/9908eac1-ad55-4202-832c-25bad17919bf

**Comment by situchan** [comment]
reviewing 2 proposals

**Comment by situchan** [comment]
@raza-ak your proposal will cause regression, which always scrolls to bottom regardless of new message arrived or not.

**Comment by situchan** [comment]
I am not able to reproduce. "New messages" floating button not appearing.


https://github.com/user-attachments/assets/8f277189-a089-47a6-9065-558f2d8b89bd

**Comment by situchan** [comment]
Instead, I reproduced in another [public room](https://staging.new.expensify.com/r/6879144773653084), where last message is whisper:


https://github.com/user-attachments/assets/e58fdf95-97fd-420b-b0b9-82fe9d571d63

**Comment by situchan** [comment]
@klajdipaja can you please share test branch?

**Comment by klajdipaja** [comment]
@situchan Here is a Draft PR #50060

**Comment by situchan** [comment]
@klajdipaja were you able to reproduce the original bug by following repro step? I am still https://github.com/Expensify/App/issues/49825#issuecomment-2386847079

**Comment by klajdipaja** [comment]
@situchan I cannot always reproduce step 4 after 3 but my emulator is really slow so if I type the email and quickly scroll up I get the New Message button and after a second the whisper too. That's actually why I fixed the unread marker logic because otherwise I would not get a New Message button.

**Comment by situchan** [comment]
reproduced. still validating solutions

**Comment by situchan** [comment]
I have no issue with @raza-ak's [solution](https://github.com/Expensify/App/issues/49825#issuecomment-2378903172) and it's simple.
@klajdipaja if you're against it, can you provide the reasoning?
I don't see why it should not scroll to bottom when hasNewestReportAction = false

**Comment by klajdipaja** [comment]
@situchan It's up to you to decide which is the best proposal. @raza-ak seems good but I am a bit worried about comment linking from commits history seems like it might affect that feature.
IMO my proposal tries to solve the root cause of the issue which is that we falsely think the lastVisibleActionCreated is equal to the latest acttion a user can see in the report. That seems to be wrong for whispers. Because of that, the unread marker on the whisper message is also unavailable.

My proposal also adds the unread marker as a sideffect:
<img width="434" alt="image" src="https://github.com/user-attachments/assets/b9d4d25e-97e7-4d82-8ab6-9ab02a94f9c6">

**Comment by situchan** [comment]
```diff
-   const hasNewestReportAction = sortedVisibleReportActions.at(0)?.created === report.lastVisibleActionCreated;
+   const hasNewestReportAction = sortedVisibleReportActions.at(0)?.created >= report.lastVisibleActionCreated;
```

This seems to fix the root cause but I found regression while testing this change.
OpenReport is not called so chat messages are not up-to-date.


https://github.com/user-attachments/assets/e1486ae0-b4a9-4a28-8d6e-bc92da2aada6


I think just fixing scroll issue here is fine, which calls OpenReport upon clicking "New messages" floating button

https://github.com/user-attachments/assets/76bcda75-0c76-4387-b46d-0b3d1fed3bc9

**Comment by situchan** [comment]
[This solution](https://github.com/Expensify/App/issues/49825#issuecomment-2400852912) is fixing the root cause but I am inclined to @raza-ak's [proposal](https://github.com/Expensify/App/issues/49825#issuecomment-2378903172) which is more regression-free, considering "New messages" floating button visibility bug (similar to https://github.com/Expensify/App/issues/49824) out of scope.
Btw, the assigned engineer will give the final call.
🎀👀🎀 C+ reviewed

**Comment by chiragsalian** [comment]
@raza-ak's [proposal](https://github.com/Expensify/App/issues/49825#issuecomment-2378903172) LGTM. Feel free to create the PR.

**Comment by raza-ak** [comment]
@chiragsalian I've applied for a job on Upwork and am currently waiting for an offer. Additionally, I'll be opening a PR and sharing it with you tomorrow.

**Comment by raza-ak** [comment]
@situchan I've opened a PR but i didn't receive an offer on upwork yet.

**Comment by raza-ak** [comment]
@situchan PR is ready for review. https://github.com/Expensify/App/pull/50623. Please review it.

**Comment by situchan** [comment]
> @situchan I've opened a PR but i didn't receive an offer on upwork yet.

No worries. BZ member will manually send offer when payment is due.
Note that there's no automatic offer for the first contributor.

**Comment by trjExpensify** [comment]
Checklist time!

**Comment by situchan** [comment]
I was not able to find the offending PR which caused this. I think the bug existed for a while.

### Regression Test Proposal
1. Create a room
2. Mention a user that is not a member of this room using
3. Notice the actionable whisper "Heads up, {user} isn't a member of this room" message appears
4. Notice the "New messages" floating button appears
5. Scroll up a little
6. Click the "New messages" floating button
7. Verify that report is scrolled to the bottom so the whisper action becomes visible

**Comment by trjExpensify** [comment]
I'm a bit confused by those steps. Why does mentioning a user in a room cause the "New messages" FAB to appear? 🤔

**Comment by situchan** [comment]
> Why does mentioning a user in a room cause the "New messages" FAB to appear? 🤔

It's another bug - https://github.com/Expensify/App/issues/49824

I think we can skip regression test for this one

**Comment by trjExpensify** [comment]
Alright yeah, I don't want to actively add a test to test for something not expected. That's counter-productive. 

Payment summary as follows: 

- $250 to @situchan for the C+ review
- $250 to @raza-ak for the fix

Situ, paid. @raza-ak, [offer sent](https://www.upwork.com/nx/wm/offer/104740462).

**Comment by trjExpensify** [comment]
@raza-ak paid, closing!
