### ISSUE TITLE
[HOLD for payment 2023-08-16] [$1000] Android emulator mWeb stuck at splash screen

### ISSUE THREAD

**Issue by Julesssss** [Expensify/App#22395]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:
- Build newDot web an unknown amount of times...
- Open NewDot mWeb via an Android emulator Chrome app

## Expected Result:
- mWeb should run as expected

## Actual Result:
- mWeb app is stuck at the splash screen

## Workaround:
- You can [use a secondary NGROK ](https://stackoverflowteams.com/c/expensify/a/10629/297) to test dev mWeb on a physical Android device 

![Screenshot 2023-07-31 at 11 11 18](https://github.com/Expensify/App/assets/10736861/1026a23e-3013-40aa-8642-ca3f9b55baf8)

## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [ ] Android / Chrome

**Version Number:** Many
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1688665141544519

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

<details><summary>Upwork Automation - Do Not Edit</summary>
    <ul>
        <li>Upwork Job URL: https://www.upwork.com/jobs/~01c9b138754f430c1c</li>
        <li>Upwork Job ID: 1677231785028624384</li>
        <li>Last Price Increase: 2023-07-31</li>
<li>Automatic offers: </li>
<ul>
<li>jjcoffee | Contributor | 25898337</li>
</ul></li>
    </ul>
</details>

**Comment by slafortune** [comment]
Is this a bug for External contributors @Julesssss ? or is this something you are looking into?

**Comment by Julesssss** [comment]
@slafortune we can keep this internal 👍

**Comment by Julesssss** [comment]
I think it's unlikely a code fix will resolve this issue, but @mananjadhav lets keep you assigned for now just in case

**Comment by Julesssss** [comment]
Hmm, there is another issue that should resolve this one, but I can't find any link to it now 😕

**Comment by Julesssss** [comment]
The other issue didn't end up resolving this.

**Comment by Julesssss** [comment]
I'll keep it for myself and look into solutions when I have a moment.

**Comment by mananjadhav** [comment]
do we have any insights on what's wrong? I don't see any logs in the emulator, no errors messages too?

**Comment by Julesssss** [comment]
I don't think this is really a bug. It's a tooling problem we have that may/may not be fixable.

**Comment by Julesssss** [comment]
What's very odd is that the issue remains after a full app uninstall/install (simulated by clearing app data).

**Comment by Julesssss** [comment]
@mananjadhav don't worry about looking into this. I'm going to try some of these potential solutions and in the unlikely case there is a code fix I'll reassign for a C+ team member 👍

**Comment by Julesssss** [comment]
I'm struggling to find anyone else with a similar problem. Posting in the open source channel and adding a $500 bounty to start with.

**Comment by Julesssss** [comment]
Reverting to previous C+ now that this is officially a bug with logs.

**Comment by b4s36t4** [comment]
is this available to externals?

**Comment by jjcoffee** [comment]
## Proposal

### Please re-state the problem that we are trying to solve in this issue.
The app gets stuck loading when running on Chrome in an emulator.

### What is the root cause of that problem?
`react-pdf` has a dependency (PDF.js) that uses `Array.prototype.at()` which is only [supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at#browser_compatibility) from Chrome v92 onwards (released 2021-07-20).

### What changes do you think we should make in order to solve the problem?
There are a couple of workarounds mentioned in [this issue](https://github.com/wojtekmaj/react-pdf/issues/1465).

1. import `core-js/features/array/at`
2. Use the [legacy](https://github.com/wojtekmaj/react-pdf#legacy-pdfjs-worker) PDF.js worker, which supports older browser versions

**Comment by Julesssss** [comment]
Given that this is a developer-only issue, it might be ideal if the solution (import or legacy lib) is only applied to local builds.

**Comment by jjcoffee** [comment]
@Julesssss Ah yeah good idea! I wasn't sure how far back we want to support older browsers. Looking at the [support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at#browser_compatibility) again, `Array.prototype.at()` has only been supported in Safari since v15.4 (Released 2022-03-15), which I guess is a bit more on the cusp of being a potential end-user problem. Or do we just treat it as developer-only until a user reports it?

**Comment by mananjadhav** [comment]
Thanks @jjcoffee for the detailed explanation and the proposal. My concern is that it loads fine for me first time, or if my emulator is on. If I stop the emulator and start again, then it will stop working. When I login for the first time, I don't see any crashes/issues. Do you have any insights on why it works first time and not later?

**Comment by jjcoffee** [comment]
@mananjadhav Hmm that sounds like it's probably a separate issue from what's described here and in the source [Slack thread](https://app.slack.com/client/T03SC9DTT/C01GTK53T8Q/thread/C01GTK53T8Q-1688665141.544519) (where people report updating Chrome fixing the issue). Just to be sure are you able to check what Chrome version you have on the emulator, and also if there are any console errors (specifically `key.split(...).at is not a function`)?

**Comment by Julesssss** [comment]
FYI I'm going OOO tomorrow so we'll take that into account when calculating the quick turnaround bonus

**Comment by jjcoffee** [comment]
[PR](https://github.com/Expensify/App/pull/24068) ready for review! cc @mananjadhav

**Comment by Julesssss** [comment]
^ The bonus should apply, I was ooo for two working days.

**Comment by mananjadhav** [comment]
In terms of checklist, I don't think we have any offending PR. Neither do we need any regression steps as it is device compatibility issues.

**Comment by Julesssss** [comment]
Yeah lets skip the checklist here, it was a dev only issue.

**Comment by mananjadhav** [comment]
@slafortune Can you post the payment summary here for the payout?

**Comment by slafortune** [comment]
External issue reporter - no payment, internal report
 Contributor that fixed the issue - @jjcoffee $1500
 Contributor+ that helped on the issue and/or PR - @mananjadhav $1500, requested via NewDot manual requests 

Speed bonus should apply, solution and pr was presented within a day.

**Comment by JmillsExpensify** [comment]
Reviewed the details for @mananjadhav. $1,500 is approved for payment in NewDot based on the summary above.
