### ISSUE TITLE
[HOLD for payment 2022-12-02] [$1000] Chat - Sender name flickers for a moment when the first message among many sent at the same time is deleted reported by @huzaifa99

### ISSUE THREAD

**Issue by kavimuru** [Expensify/App#12289]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

## Action Performed:

1. Select any chat
2. Send several messages at the same time (in a DM, in a policy chat chat, etc.)
3. Delete the first message 

## Expected Result:
The sender's info shouldn't disappear momentarily. Instead the sender info should move/float down to the next oldest message. 

## Actual Result:
The sender info disappears momentarily. This is due our design of only showing the the sender's info on the first/oldest message, when several are sent within minutes of each other. 

## Workaround:
No workarounds

## Platform:

Where is this issue occurring?

- Web
- Desktop

**Version Number:** v1.2.21-4.
**Reproducible in staging?:** y
**Reproducible in production?:** y
**Email or phone of affected tester (no customers):** 
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Notes/Photos/Videos:** 

https://user-images.githubusercontent.com/43996225/198912205-8cd19bdb-b78b-461b-b85a-2481a60d4971.mp4

https://user-images.githubusercontent.com/43996225/198912211-43cdb967-a327-4c28-8418-23a0def78be4.mp4

**Expensify/Expensify Issue URL:** 
**Issue reported by:** @huzaifa-99
**Slack conversation:** https://expensify.slack.com/archives/C01GTK53T8Q/p1666995834532459

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by aldo-expensify** [comment]
Reapplying the `AutoAssignerTriage` because @ntrepanier was assigned

**Comment by JmillsExpensify** [comment]
Alright, I will circle back to this one tomorrow. I want to test and update the reproduction steps before I triage this one.

**Comment by JmillsExpensify** [comment]
Jumping in to test now.

**Comment by JmillsExpensify** [comment]
Opening this issue up for proposals. Upwork job is here: https://www.upwork.com/jobs/~01a3019c47c3980a30.

**Comment by JmillsExpensify** [comment]
Oh and I should clarify, it's helpful to also test this issue on mobile (iOS/Android), because the flicker/disappearing header doesn't happen.

**Comment by JmillsExpensify** [comment]
Still waiting for proposals

**Comment by puneetlath** [comment]
@puneetlath this is one of the oldest issues in the /App repo. To help us clear out the large backlog of bugs, can you:  
- Decide whether any proposals currently meet our guidelines and can be approved as-is 
- For any that can't, please take this issue internal and treat it as one of your highest priorities 
- If you have any questions, don't hesitate to start a discussion in #bug-zero

**Comment by JmillsExpensify** [comment]
Thanks, done!

**Comment by s77rt** [comment]
### Proposal
```diff
diff --git a/src/libs/ReportActionsUtils.js b/src/libs/ReportActionsUtils.js
index ae04dc86c..58ef88367 100644
--- a/src/libs/ReportActionsUtils.js
+++ b/src/libs/ReportActionsUtils.js
@@ -73,7 +73,12 @@ function getMostRecentIOUReportActionID(reportActions) {
  * @returns {Boolean}
  */
 function isConsecutiveActionMadeByPreviousActor(reportActions, actionIndex) {
-    const previousAction = reportActions[actionIndex + 1];
+    let previousActionIndex = actionIndex + 1;
+    while (reportActions[previousActionIndex]?.action?.pendingAction === CONST.RED_BRICK_ROAD_PENDING_ACTION.DELETE) {
+        previousActionIndex++;
+    }
+
+    const previousAction = reportActions[previousActionIndex];
     const currentAction = reportActions[actionIndex];
 
     // It's OK for there to be no previous action, and in that case, false will be returned
```

### Details
The issue is that deleted messages are not deleted immediately. On the `isConsecutiveActionMadeByPreviousActor` function, those to be deleted messages are technically still there. Thus such a message will meet the set criteria with the message below it and that message (the one below) will be considered grouped (with the first message that's technically there but it will be deleted).
The fix is easy and it's just to ignore those to be deleted messages. I made a while loop to fetch the first previous item that is not marked to be deleted.


https://user-images.githubusercontent.com/16493223/202852687-245696e5-4624-48cf-b292-b422583fca73.mp4

**Comment by alex-mechler** [comment]
Going to take this over as part of the focus on WAQ so we can get this bug done quickly.

**Comment by alex-mechler** [comment]
@puneetlath the solution was largely what @s77rt had proposed. Can you make sure they get paid out for this? Without their proposal this would have taken much longer

**Comment by robertjchen** [comment]
Was able to reproduce this locally as well, investigating.

**Comment by robertjchen** [comment]
my bad for the confusion, I had an old version of the GH issue opened and it still had the old labels. Ignore my statement above 👍

**Comment by JmillsExpensify** [comment]
I'm not sure what happened with the assignments though I know that @puneetlath is out, so I'll happily take this one while he's on vacay. 

@s77rt can you make sure to apply to the [Upwork job](https://www.upwork.com/jobs/~01a3019c47c3980a30) so we can get you paid out. 

@mananjadhav I've invited you to the job, please accept!

**Comment by JmillsExpensify** [comment]
> [@puneetlath / @alex-mechler] The PR that introduced the bug has been identified. Link to the PR:
 [@puneetlath / @alex-mechler] The offending PR has been commented on, pointing out the bug it caused and why, so the author and reviewers can learn from the mistake. Link to comment:
 [@puneetlath / @alex-mechler] A discussion in #expensify-bugs has been started about whether any other steps should be taken (e.g. updating the PR review checklist) in order to catch this type of bug sooner. Link to discussion:

Then finally, @alex-mechler can you please handle the first three todos on the BugZero checklist? Once we handle those then I'll circle back on the regression test based on the QA steps in the linked PR.

**Comment by s77rt** [comment]
@JmillsExpensify Applied

**Comment by JmillsExpensify** [comment]
Ah yes, let's also make sure that @huzaifa99 applies as well for the reporting bonus.

**Comment by alex-mechler** [comment]
Tried digging into finding an offending PR, but I'm having some issues with it. As far back as I can get to compile, I can still reproduce this. I've started a slack thread here https://expensify.slack.com/archives/C01SKUP7QR0/p1669683809688769

**Comment by alex-mechler** [comment]
@JmillsExpensify after spending time trying to find any pr that could have introduced this, I was unable to find one. I spent a decent amount of time, but even as far back as I could go without running into major compilation errors, this was still reproducible. I'm not sure we will be able to find the root cause in a decent amount of time. I don't think the best use of my time is to keep digging down that hole. Thoughts?

**Comment by JmillsExpensify** [comment]
Ok, I think that's fine, though obviously not ideal. Given that we have a bunch of other bugs to still handle, I'm good with moving on. @puneetlath Can weight in too when he returns.

**Comment by JmillsExpensify** [comment]
P.S. @huzaifa99 we're still waiting for you to apply to the Upwork job.

**Comment by JmillsExpensify** [comment]
As for the regression test, I can get started on that now. I think this is fairly useful to add, even if it's largely cosmetic. 

>Send a bank of several messages from the same account
Delete a message in the middle of the bank of messages
Verify the header with the name appears as expected, only at the top of the bank of messages
Delete the first message in the bank of messages
Verify the header still appears, and does not flicker
Repeat 2-5 with networking disabled

**Comment by alex-mechler** [comment]
I think that regression test looks good to me, its the same steps I used to verify my fix worked, so it makes sense 👍

**Comment by JmillsExpensify** [comment]
Oh yeah haha I pulled it from your PR 😄. I'll create a separate regression issue for Applause. Ideally we don't have to create a special test just for this.

**Comment by JmillsExpensify** [comment]
Regression test is linked above.

**Comment by huzaifa-99** [comment]
> P.S. @huzaifa99 we're still waiting for you to apply to the Upwork job.

@JmillsExpensify sry missed this, just applied now. Thanks

**Comment by huzaifa-99** [comment]
I think you incorrectly tagged @huzaifa99, that is another person. The issue was reported on slack [here](https://expensify.slack.com/archives/C01GTK53T8Q/p1666995834532459)

**Comment by JmillsExpensify** [comment]
Ok thanks! That's who appears in the issue description, so that's why I kept tagging that user. However, I agree with you that's a mistake so I'm updating above to set the record straight.

**Comment by JmillsExpensify** [comment]
All contributors are hired. Given that the PR in this case is internal and is already on staging, I'm going to go ahead and issue payments. Here's we landed:

- External issue reporter: @huzaifa-99 $250
- ✅ Contributor: @s77rt $1,000
- ✅ Contributor+: @mananjadhav $1,000

I'll close this issue out as soon as @huzaifa-99 accepts the offer via Upwork and I pay him out.

**Comment by huzaifa-99** [comment]
@JmillsExpensify Accepted thanks. Also apologies as I also did not saw it in the issue description before.

**Comment by JmillsExpensify** [comment]
All good! We got it straight. Everyone is paid out at this point and we have a regression test in a separate issue. Closing.
