### ISSUE TITLE
Room - Whisper to invite member in public room is not displayed

### ISSUE THREAD

**Issue by m-natarajan** [Expensify/App#43900]
If you haven’t already, check out our [contributing guidelines](https://github.com/Expensify/ReactNativeChat/blob/main/contributingGuides/CONTRIBUTING.md) for onboarding and email contributors@expensify.com to request to join our Slack channel!
___

**Version Number:** 1.4.85-0
**Reproducible in staging?:** y
**Reproducible in production?:** n
**If this was caught during regression testing, add the test name, ID and link from TestRail:** https://expensify.testrail.io/index.php?/tests/view/4642018&group_by=cases:section_id&group_order=asc&group_id=296763
**Email or phone of affected tester (no customers):**
**Logs:** https://stackoverflow.com/c/expensify/questions/4856
**Expensify/Expensify Issue URL:**
**Issue reported by:** Applause internal team
**Slack conversation:**

## Action Performed:
1. Login with Gmail account
2. Create a Public Room
3. Mention a user who is not a member of the room

## Expected Result:
There should be a whisper asking the user if they want to invite the mentioned user to the room or do nothing

## Actual Result:
Whisper to invite member in public room is not displayed ( this issue occurs only with the Gmail account)

## Workaround:
unknown
## Platforms:

Which of our officially supported platforms is this issue occurring on?
- [x] Android: Native
- [x] Android: mWeb Chrome
- [ ] iOS: Native
- [ ] iOS: mWeb Safari
- [x] MacOS: Chrome / Safari
- [ ] MacOS: Desktop

## Screenshots/Videos

https://github.com/Expensify/App/assets/38435837/d0206082-e6ed-4889-bf93-c47198d6159d

</details>

[View all open jobs on GitHub](https://github.com/Expensify/App/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22)

**Comment by m-natarajan** [comment]
@johnmlee101 FYI I haven't added the External label as I wasn't 100% sure about this issue. Please take a look and add the label if you agree it's a bug and can be handled by external contributors

**Comment by m-natarajan** [comment]
We think that this bug might be related to  #vip-vsb

**Comment by johnmlee101** [comment]
I believe its caused by https://github.com/Expensify/Web-Expensify/pull/42258

**Comment by johnmlee101** [comment]
bringing discussion to slack: https://expensify.slack.com/archives/C07J32337/p1718741313845649

**Comment by marcaaron** [comment]
Fix on staging now and testing well so gonna check it off.
